//This file was generated by script swreg2regmap.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_x1sw 2
#define KNN_x2sw 3
#define KNN_y1sw 4
#define KNN_y2sw 5
#define KNN_zsw 6
#define dummy 7
